"""Search data access interface — all DB queries needed by use cases."""

from typing import Protocol


class SearchDataAccess(Protocol):
    """Interface for document search data access."""

    def get_sub_documents(self, document_id: int) -> list: ...
    def get_completed_documents(self, collection_id: int) -> list: ...
    def get_collections_by_account(self, account_id: str) -> list: ...
    def get_collection_by_collection_id(self, collection_id: str): ...
    def get_all_collections(self) -> list: ...
    def get_collection_library_card(self, collection_id: int): ...
    def get_library_card_for_sub_doc(self, sub_doc_id: int): ...
    def get_library_card_by_doc_id(
        self, doc_id: str, sub_doc_id: int | None = None
    ): ...
    def get_chunk(
        self, document_id: int, chunk_index: int, sub_doc_id: int | None = None
    ): ...
    def get_chunks_batch(
        self, document_id: int, chunk_specs: list[tuple[int, int | None]]
    ) -> dict: ...
    def get_library_cards_by_doc_ids(self, doc_ids: list[str]) -> dict: ...
    def count_sub_documents(self, document_id: int) -> int: ...
    def get_account_by_name(self, name: str): ...
    def save_account(self, account) -> None: ...
