from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class SearchPlan(BaseModel):
    """Search plan generated by query planner."""

    strategy: str
    queries: List[str]
    reasoning: str
    total_unique_results: Optional[int] = None
    sub_answers_count: Optional[int] = None
