from __future__ import annotations

from pydantic import BaseModel


class SearchPlan(BaseModel):
    """Search plan generated by query planner."""

    strategy: str
    queries: list[str]
    reasoning: str
    total_unique_results: int | None = None
    sub_answers_count: int | None = None
