from __future__ import annotations

from pydantic import BaseModel


class SubAnswer(BaseModel):
    """Answer to a sub-question generated by the planner."""

    question: str
    answer: str
    has_answer: bool
    num_results: int
